### ISSUE TITLE
"TypeError: NoneType object is not callable" when starting ovos-tts-server

### ISSUE THREAD

**Issue by technout** [NeonGeckoCom/neon-tts-plugin-coqui#88]
Hi, trying to run it on Ubuntu 20.04 with Python 3.8 but got some error:

Command: ovos-tts-server --engine neon-tts-plugin-glados --cache

Output:
```2022-12-03 20:30:09.287 - OVOS - ovos_config.models:load_local:95 - DEBUG - Configuration /home/<user>/.local/lib/python3.8/site-packages/ovos_config/mycroft.conf loaded
2022-12-03 20:30:09.348 - OVOS - ovos_config.models:load_local:99 - DEBUG - Configuration '/etc/mycroft/mycroft.conf' not defined, skipping
2022-12-03 20:30:09.411 - OVOS - ovos_config.models:load_local:99 - DEBUG - Configuration '/home/<user>/.config/mycroft/web_cache.json' not defined, skipping
2022-12-03 20:30:09.476 - OVOS - ovos_config.models:load_local:99 - DEBUG - Configuration '/home/<user>/.config/mycroft/mycroft.conf' not defined, skipping
2022-12-03 20:30:09.539 - OVOS - ovos_config.models:load_local:99 - DEBUG - Configuration '/etc/xdg/mycroft/mycroft.conf' not defined, skipping
2022-12-03 20:30:09.602 - OVOS - ovos_config.models:load_local:99 - DEBUG - Configuration '/etc/xdg/xdg-ubuntu/mycroft/mycroft.conf' not defined, skipping
2022-12-03 20:30:09.666 - OVOS - ovos_config.models:load_local:99 - DEBUG - Configuration '/home/<user>/.mycroft/mycroft.conf' not defined, skipping
2022-12-03 20:30:11.226 - OVOS - ovos_plugin_manager.g2p:create:98 - DEBUG - Loaded plugin dummy
Traceback (most recent call last):
  File "/home/<user>/.local/bin/ovos-tts-server", line 8, in <module>
    sys.exit(main())
  File "/home/<user>/.local/lib/python3.8/site-packages/ovos_tts_server/__main__.py", line 29, in main
    start_tts_server(args.engine, port=args.port, host=args.host, cache=bool(args.cache))
  File "/home/<user>/.local/lib/python3.8/site-packages/ovos_tts_server/__init__.py", line 50, in start_tts_server
    TTS = engine(config={"persist_cache": cache})  # this will cache every synth even across reboots
  File "/home/<user>/.local/lib/python3.8/site-packages/neon_tts_plugin_glados/__init__.py", line 35, in __init__
    self.glados = torch.jit.load(model)
  File "/home/<user>/.local/lib/python3.8/site-packages/torch/jit/_serialization.py", line 161, in load
    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)
RuntimeError: Unknown qengine
```

I did succesfully install:
sudo apt install espeak-ng
pip3 install ovos-tts-server
pip3 install neon-tts-plugin-glados
pip3 install ovos-tts-plugin-server

What did i do wrong? :)

**Comment by technout** [comment]
> @technout try neon-tts-plugin-coqui instead of neon-tts-plugin-glados

After installing it with: pip3 install neon-tts-plugin-coqui
I tried: ovos-tts-server --engine neon-tts-plugin-coqui --cache

Got this error:
```
2022-12-11 - OVOS - ovos_plugin_manager.utils:load_plugin:104 - WARNING - Could not find the plugin mycroft.plugin.tts.neon-tts-plugin-coqui
Traceback (most recent call last):
  File "/home/<user>/.local/bin/ovos-tts-server", line 8, in <module>
    sys.exit(main())
  File "/home/<user>/.local/lib/python3.8/site-packages/ovos_tts_server/__main__.py", line 29, in main
    start_tts_server(args.engine, port=args.port, host=args.host, cache=bool(args.cache))
  File "/home/<user>/.local/lib/python3.8/site-packages/ovos_tts_server/__init__.py", line 50, in start_tts_server
    TTS = engine(config={"persist_cache": cache})  # this will cache every synth even across reboots
TypeError: 'NoneType' object is not callable
```

**Comment by technout** [comment]
ovos-tts-server --engine neon-tts-plugin-coqui --cache
This command should work, right? Why do i still get the above error?

**Comment by NeonBohdan** [comment]
Here is the [PR about this ](https://github.com/NeonGeckoCom/neon-tts-plugin-coqui/pull/84/files)
Try 
`ovos-tts-server --engine neon-tts-plugin-coqui` or
`ovos-tts-server --engine coqui`

**Comment by technout** [comment]
Thanks for the reply, the first command give the same TypeError.
Second command starts the server, when trying to connect to http://localhost:9666/ it gives an 404, also noted in the the log as: "GET / HTTP/1.1" 404 -
But does this not start a different engine then --engine neon-tts-plugin-coqui or is it the same?

**Comment by Theodotus1243** [comment]
Try [Gradio demo](https://huggingface.co/spaces/neongeckocom/neon-tts-plugin-coqui), which you can deploy localy

**Comment by technout** [comment]
Thanks for the huggingface.co tip, interesting! But i really want to run my original request locally, that should work right?

**Comment by NeonBohdan** [comment]
Once this https://github.com/NeonGeckoCom/neon-tts-plugin-coqui/pull/93 pull request will be accepted you will be able to use coqui with ovos-tts-server

Simpy run
```
docker pull ghcr.io/neongeckocom/coqui-tts:latest

docker run -p 8080:9666 coqui-tts
```

Open browser and request 
`http://localhost:8080/synthesize/hello` or `http://localhost:8080/synthesize/Привіт?lang=uk`

If you want to setup it without docker simply follow [Dockerfile](https://github.com/NeonGeckoCom/neon-tts-plugin-coqui/blob/dev/Dockerfile)

Fill free to reopen
