### ISSUE TITLE
[BUG] I get error message "KeyError: 'en-us'" when I use "CoquiTTS()"

### ISSUE THREAD

**Issue by cahya-wirawan** [NeonGeckoCom/neon-tts-plugin-coqui#99]
### Description

Hi,
I get error message **KeyError: 'en-us'** when I use "CoquiTTS()"

```
from neon_tts_plugin_coqui import CoquiTTS
coquiTTS = CoquiTTS()
```
The error message is:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/neon_tts_plugin_coqui/__init__.py", line 69, in __init__
    self._init_model({"lang": lang})
  File "/usr/local/lib/python3.9/site-packages/neon_tts_plugin_coqui/__init__.py", line 188, in _init_model
    synt = self._init_synthesizer(lang)
  File "/usr/local/lib/python3.9/site-packages/neon_tts_plugin_coqui/__init__.py", line 240, in _init_synthesizer
    synt = importer.load_pickle("tts_models", "model")
  File "/usr/local/lib/python3.9/site-packages/torch/package/package_importer.py", line 256, in load_pickle
    result = unpickler.load()
  File "/usr/local/lib/python3.9/pickle.py", line 1212, in load
    dispatch[key[0]](self)
  File "/usr/local/lib/python3.9/pickle.py", line 1528, in load_global
    klass = self.find_class(module, name)
  File "/usr/local/lib/python3.9/site-packages/torch/package/_package_unpickler.py", line 25, in find_class
    mod = self._importer.import_module(module)
  File "/usr/local/lib/python3.9/site-packages/torch/package/package_importer.py", line 134, in import_module
    return self._gcd_import(name)
...
  File "/usr/local/lib/python3.9/site-packages/torch/package/package_importer.py", line 431, in _find_and_load
    return self._do_find_and_load(name)
  File "/usr/local/lib/python3.9/site-packages/torch/package/package_importer.py", line 421, in _do_find_and_load
    module = self._load_module(name, parent)
  File "/usr/local/lib/python3.9/site-packages/torch/package/package_importer.py", line 371, in _load_module
    return self._make_module(name, cur.source_file, isinstance(cur, _PackageNode), parent)  # type: ignore[attr-defined]
  File "/usr/local/lib/python3.9/site-packages/torch/package/package_importer.py", line 354, in _make_module
    exec(code, ns)
  File "<torch_package_8>.TTS/tts/utils/text/phonemizers/__init__.py", line 20, in <module>
KeyError: 'en-us'

```

### Steps to Reproduce

```
from neon_tts_plugin_coqui import CoquiTTS
coquiTTS = CoquiTTS()
```

### Other Notes
Version:
neon-tts-plugin-coqui     0.7.2
_No response_

**Comment by NeonBohdan** [comment]
See [here](https://github.com/NeonGeckoCom/neon-tts-plugin-coqui/blob/dev/neon_tts_plugin_coqui/configs.py)  what lang codes coqui tts have 
Try use `en` instead of `en-us`

**Comment by cahya-wirawan** [comment]
Hi @NeonBohdan 
Thanks for the info. It seems I just forget to install espeak-ng. CoquiTTS() works after I install it.
